name: Deploy with Docker Run

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Pull latest image
      run: docker pull poridhi/nav-backend:v1.7
    
    - name: Stop existing container
      run: |
        docker stop nav-backend || true
        docker rm nav-backend || true
      continue-on-error: true
    
    - name: Deploy container
      run: |
        docker run -d \
          --name nav-backend \
          --restart always \
          poridhi/nav-backend:v1.7
